export interface Match {
  results: String,
  attendance: String,
  matchID: number,
  startTime: Date,
  endTime: Date,
  roundID: number,
  name: String,
  location: String,
  description: String,
  playerOneID:number,
  playerTwoID:number,
  playerOneName:string,
  playerTwoName:string,
}

export const initMatch = {
  results: '',
  attendance: '',
  matchID: -1,
  startTime: new Date(),
  endTime: new Date(),
  roundID: 1,
  name: '',
  location: '',
  description: '',
  playerOneID: -1,
  playerTwoID: -1,
  playerOneName: '',
  playerTwoName: '',
};
